version: '3'
services:

  app:
    build: 
      dockerfile: Dockerfile
      context: ..
    environment:
      - PG_PASSWORD=postgrespassword
      - PG_USER=user
      - PG_DB=consumer_importer
      - PG_PORT=5000
      - PG_HOST=localhost
      - FILE_REPOSITORY=../file-repository/
    volumes:
      - "../file-repository:/file-repository"