version: '2'
services:

  app:
    build: 
      dockerfile: Dockerfile
      context: ..
    environment:
      - PG_PASSWORD=p0stgr3s
      - PG_USER=pguser
      - PG_DATABASE=consumer_importer
      - PG_PORT=5432
      - PG_HOST=postgresdb
      - FILE_REPOSITORY=file-repository/
    volumes:
      - "../file-repository:/file-repository"