version: '2'

services:
  postgresdb:
    extends:
      file: postgres.yml
      service: postgresdb
    networks:
      - "consumer-importer-network"

  app:
    extends:
      file: consumer-importer.yml
      service: app
    networks:
      - "consumer-importer-network"

volumes:
  postgresdata:

networks:
  consumer-importer-network: