version: '2'
services:

  postgresdb:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=p0stgr3s
      - POSTGRES_USER=pguser
      - POSTGRES_DB=consumer_importer
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - "postgresdata:/var/lib/postgresql/data"

volumes:
    postgresdata: